### PR TITLE
Rename stow script, remove pre-catkin roslib call

### PR DESCRIPTION
**Pull request by paulbovbel**

### CODE REVIEW

**Comment by paulbovbel** [comment]
@TheDash, please find appropriate license info for stow script and then merge

**Comment by UltronDestroyer** [comment]
The only thing I can find that is similar is this https://github.com/ros-industrial/universal_robot/blob/indigo-devel/ur_driver/test_move.py but it has no license. 

I originally took stow.py from our aus02 husky repo which was written by us. So its safe to say it's ours.

**Comment by paulbovbel** [comment]
+1

**Comment by UltronDestroyer** [comment]
Merged.

**Pull request merged**
